### PR TITLE
link to GitHub from MetaCPAN

### PR DESCRIPTION
**Pull request by szabgab**

### CODE REVIEW

**Comment by szabgab** [comment]
It would be nice if you could upload it to CPAN as that would enable it to enter the CPAN PR challenge and @neilbowers might be able to direct people to the module.

**Comment by borisdaeppen** [comment]
I'll wait for some smoketests, can you also have a short look if I missed something?
(Now that I think about it.... adding you to contributors)
https://metacpan.org/release/BORISD/EBook-MOBI-0.71-TRIAL
I'll wait for your feedback
----Ursprüngliche Nachricht----
Von : notifications@github.com
Datum : 24/09/2015 - 15:02 (CEST)
An : EBook--MOBI@noreply.github.com
Cc : boris_daeppen@bluewin.ch
Betreff : Re: [EBook--MOBI] link to GitHub from MetaCPAN (#33)
It would be nice if you could upload it to CPAN as that would enable it to enter the CPAN PR challenge and @neilbowers might be able to direct people to the module.

**Comment by szabgab** [comment]
ok, I sent you one from Mac and one from Linux.

**Comment by borisdaeppen** [comment]
This released version should have all your commits included:

https://metacpan.org/release/BORISD/EBook-MOBI-0.72

**Pull request merged**
